# AI Engine
HF_API_KEY = "your_hugging_face_token_here"

# Counselor Portal Credentials
C_USER = "admin_counselor"
C_PASS = "SafeSchool@2026"

# Email Alert System (Gmail SMTP)
SMTP_USER = "yourschool@gmail.com"
SMTP_PASS = "your_gmail_app_password"
COUNSELOR_EMAIL = "safety@school.com"
